name: Generate Contributors

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  contrib:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Contributors Grid
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
